[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_rounds = 200
evm_version="paris"
fs_permissions = [{ access = "read", path = "./broadcast" }]

# --chains--
[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"
goerli = "${RPC_GOERLI}" 
bsc = "${RPC_BSC}"
bsctest = "${RPC_BSC_TEST}"
base = "${RPC_BASE}"
baseSepolia = "${RPC_BASE_SEPOLIA}"
baseGoerli = "${RPC_BASE_GOERLI}"
avax = "${RPC_AVAX}"
avaxTest = "${RPC_AVAX_FUJI}"

localhost = "${RPC_LOCALHOST}"

# --scans--
[etherscan]
# Ethereum
mainnet = { key = "${ETHERSCAN_KEY}"}
sepolia = { key = "${ETHERSCAN_KEY}", chain = "11155111"}
goerli = { key = "${ETHERSCAN_KEY}", chain = "5" }
# Binance Smart Chain
bsc = { key = "${BSCSCAN_KEY}", chain = "56" }
bsctest = { key = "${BSCSCAN_KEY}", chain = "97" }
# Base Chain
base = { key = "${BASESCAN_KEY}", chain = "8453"}
baseSepolia = { key = "${BASESCAN_SEPOLIA_KEY}", chain = "84532", url = "https://base-sepolia.blockscout.com/api" }
baseGoerli = { key = "${BASESCAN_KEY}", chain = "84531" }
# Avalanche
avax = {key="${SNOWTRACE_KEY}", chain="43114", url='https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan'}
avaxTest = {key="${SNOWTRACE_KEY}", chain="43113", url='https://api.routescan.io/v2/network/testnet/evm/43113/etherscan'}

[fuzz]
runs = 1000
max_test_rejects=50000
